---
# handlers file for src/roles/php
- name: Restart nginx
  become: true
  service:
    name: nginx
    state: restarted

- name: Restart httpd
  become: true
  service:
    name: httpd
    state: restarted

- name: Restart php-fpm
  become: true
  service:
    name: php-fpm
    state: restarted
